routes/users.py
from flask import Blueprint, redirect, render_template, url_for, session
from models import save_services, get_services
from flask_login import login_required, current_user
from decorator import user_required, redirect_to_worker_profile
from decorator import complete_profile


user = Blueprint("user", __name__)


@user.route("/")
@complete_profile
@redirect_to_worker_profile
def home():
    # save_services()
    alert = session.pop("alert", None)
    bg_color = session.pop("bg_color", None)
    serv = get_services()
    return render_template(
        "home.html", home=True, services=serv, alert=alert, bg_color=bg_color
    )


# message
@user.route("/message")
@complete_profile
@login_required
def message():
    return render_template("message.html")

routes/worker.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from flask_login import (
    login_user,
    logout_user,
    logout_user,
    login_required,
    current_user,
)
from models import WorkerProfile, get_services
from decorator import worker_required
import cloudinary.uploader
import cloudinary_config
from extensions import mail, db

worker = Blueprint("worker", __name__)


@worker.route("/home")
@login_required
@worker_required
def home():
    alert = session.pop("alert", None)
    bg_color = session.pop("bg_color", None)
    return render_template(
        "worker/home.html", home=True, alert=alert, bg_color=bg_color
    )


@worker.route("/update_profile", methods=["GET", "POST"])
@login_required
@worker_required
def update_profile():
    alert = session.pop("alert", None)
    bg_color = session.pop("bg_color", None)
    servs = get_services()
    if request.method == "POST":
        company = request.form.get("company")
        description = request.form.get("description")
        rate = request.form.get("rate")
        work_pic1 = request.files.get("work_pic1")
        work_pic2 = request.files.get("work_pic2")
        work_pic3 = request.files.get("work_pic3")
        service_offered = request.form.get("service_offered")
        user = current_user.id
        print(rate, "rate")
        if not company:
            alert = "Please enter your company name"
            bg_color = "danger"
            return render_template(
                "worker/update_profile.html",
                alert=alert,
                bg_color=bg_color,
                company=company,
                description=description,
                rate=rate,
                work_pic1=work_pic1,
                work_pic2=work_pic2,
                work_pic3=work_pic3,
                service_offered=service_offered,
            )
        if not description:
            alert = "Please enter your description"
            bg_color = "danger"
            return render_template(
                "worker/update_profile.html",
                alert=alert,
                bg_color=bg_color,
                company=company,
                description=description,
                rate=rate,
                work_pic1=work_pic1,
                work_pic2=work_pic2,
                work_pic3=work_pic3,
                service_offered=service_offered,
            )
        if not service_offered:
            alert = "Please enter your service offered"
            bg_color = "danger"
            return render_template(
                "worker/update_profile.html",
                alert=alert,
                bg_color=bg_color,
                company=company,
                description=description,
                rate=rate,
                work_pic1=work_pic1,
                work_pic2=work_pic2,
                work_pic3=work_pic3,
                service_offered=service_offered,
            )
        if not work_pic1 and not work_pic2 and not work_pic3:
            alert = "Please enter your work pictures"
            bg_color = "danger"
            return render_template(
                "worker/update_profile.html",
                alert=alert,
                bg_color=bg_color,
                company=company,
                description=description,
                rate=rate,
                work_pic1=work_pic1,
                work_pic2=work_pic2,
                work_pic3=work_pic3,
                service_offered=service_offered,
            )

        print(
            "company",
            company,
            "desc",
            description,
            "rate",
            rate,
            "work_pic1",
            work_pic1,
            "work_pic2",
            work_pic2,
            "work_pic3",
            work_pic3,
            "service_offered",
            service_offered,
            "user",
            user,
        )

        work_pics = [work_pic1, work_pic2, work_pic3]
        cloudinary_img_urls = []

        for res in work_pics:
            result = cloudinary.uploader.upload(
                res,
                folder="service_connect",
                transformation=[{"width": 176, "height": 176, "crop": "fill"}],
            )
            image_url = result["secure_url"]
            cloudinary_img_urls.append(image_url)

        worker_profile = WorkerProfile(
            company=company,
            description=description,
            rate=rate,
            work_pic1=cloudinary_img_urls[0],
            work_pic2=cloudinary_img_urls[1],
            work_pic3=cloudinary_img_urls[2],
            service_offered=service_offered,
            user=user,
        )
        db.session.add(worker_profile)
        try:
            db.session.commit()
            session["alert"] = "Profile updated successfully"
            session["bg_color"] = "success"
        except IntegrityError as e:
            print(e, "Worker Profile Not Added")
            db.session.rollback()
            session["alert"] = "Error updating profile"
            session["bg_color"] = "danger"
        except Exception as e:
            print(e, "Worker Profile Not Added")
            db.session.rollback()
            session["alert"] = "Error updating profile"
            session["bg_color"] = "danger"
        return redirect(url_for("worker.home"))

    return render_template(
        "worker/update_profile.html", alert=alert, bg_color=bg_color, servs=servs
    )

templates/worker/home.html
{% extends 'layout.html' %}
{% block content %}
<section>
    <div class="container py-5">
      <div class="row">
        <div class="col">
        </div>
      </div>
  
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4 bg-dark">
            <div class="card-body text-center">
              <img src="{{current_user.profile_picture}}" alt="avatar"
                class="rounded-circle img-fluid img-thumbnail" style="width: 150px;">
              <h5 class="mt-3 text-white">{{current_user.username}}</h5>
              <p class="text-muted mb-3">{{current_user.worker_profile[0].services.name}}</p>
              <!-- <p class="text-muted mb-4">Bay Area, San Francisco, CA</p> -->
              <p class="text-dark mb-2 fw-normal badge bg-warning">Basic User</p>
              <div class="d-flex justify-content-center mb-2">
                <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary shadow-none">Subscribe</button>
                <a href="{{url_for('user.message')}}" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-primary text-white ms-1 position-relative shadow-none text-decoration-none">Messages
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                        9+
                        <span class="visually-hidden">unread messages</span>
                    </span>
                </a>
              </div>
            </div>
          </div>
          <div class="card mb-4 mb-lg-0">
            <div class="card-body p-0">
              <ul class="list-group list-group-flush rounded-3">
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fas fa-globe fa-lg text-warning"></i>
                  <p class="mb-0">https://mdbootstrap.com</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                  <p class="mb-0">mdbootstrap</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                  <p class="mb-0">@mdbootstrap</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                  <p class="mb-0">mdbootstrap</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                  <p class="mb-0">mdbootstrap</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="card mb-4 bg-info text-white">
            <div class="card-body">
              <!-- <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Full Name</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">Johnatan Smith</p>
                </div>
              </div> -->
              <!-- <hr> -->
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-white mb-0">{{current_user.email}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Phone</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-white mb-0">{{current_user.phone}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Company</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-white mb-0">{{current_user.worker_profile[0].company}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Rate</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-white mb-0">{% if current_user.worker_profile[0].rate %}{{current_user.worker_profile[0].rate}}{% else %}Contact for price{% endif %}</p>
                </div>
              </div>
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-dark fw-normal" style="cursor: pointer;">
                <a class="text-white text-decoration-none" data-bs-toggle="modal" data-bs-target="#exampleModal">Edit Profile</a>
            </span>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                  </p>
                  <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                  <div class="progress rounded mb-2" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                  </p>
                  <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                  <div class="progress rounded mb-2" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- Modal -->
<div class="modal fade" id="exampleModal" data-bs-backdrop="static" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Update Profile</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="">
            <label for="company" class="" style="font-size: .9rem;">Company</label>
            <input type="text" value="{{current_user.worker_profile[0].company}}" class="form-control shadow-none" style="font-size: .9rem;" required>
          </form>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> -->
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
    {% endblock %}

templates/worker/update_profile.html
{% extends 'layout.html' %}

{% block content %}

<div class="container" id="list_admins" style="display: flex; justify-content: space-between; align-items: center; width: 40rem; margin-top: 7rem">
</div>
<div class="form-body">
    <div class="row">
        <div class="form-holder mx-auto border" style="border: 2px solid rgb(122, 123, 126); border-radius: 16px; padding: 50px; width: 40rem; box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;">
            <div class="form-content">
                <div class="form-items">
                    <h5 class="text-primary text-center mb-3">Complete registration</h5>
                    <!-- <p class="text-muted">Fill in the data below.</p> -->
                    <form class="requires-validation" action="" method="post" enctype="multipart/form-data">

                        <div class="col-md-12">
                            <img src="{{current_user.profile_picture}}" alt="{{current_user.username}}"
                        style="width: 3rem; cursor: pointer;" class="mx-auto d-block rounded-circle img-thumbnail" id="pp">
                           <input class="form-control shadow-none border" id="username_input" type="text" name="username" placeholder="Username" required value="{{current_user.username}}" disabled>
                           <input class="form-control shadow-none border" id="email_input" type="email" name="email" placeholder="Email" required value="{{current_user.email}}" disabled>
                           <input class="form-control shadow-none border" id="phone_input" type="tel" name="phone_number" placeholder="Phone" required value="{{current_user.phone}}" disabled>
                           <!-- radio labels -->
                           <div class="my-3">
                           <div class="form-check form-check-inline">
                               <input class="form-check-input" type="radio" name="price" id="rate" value="rate" checked>
                               <label class="form-check-label" for="rate">Rate</label>
                           </div>
                           <div class="form-check form-check-inline">
                               <input class="form-check-input" type="radio" name="price" id="contact_price" value="contact_price">
                               <label class="form-check-label" for="contact_price">Contact for price</label>
                           </div>
                        </div>
                           <input class="form-control shadow-none border" id="rate_input" type="number" name="rate" placeholder="Rate">
                           <input class="form-control shadow-none border" id="company_name_input" type="text" name="company" placeholder="company Name">
                           <!-- descrption -->
                           <textarea class="form-control shadow-none border mt-3" id="description_input" name="description" placeholder="Description" rows="3"></textarea>
                           <input class="form-control shadow-none border d-none" id="work_pic1" type="file" name="work_pic1" placeholder="Work Picture">
                           <input class="form-control shadow-none border d-none" id="work_pic2" type="file" name="work_pic2" placeholder="Work Picture">
                           <input class="form-control shadow-none border d-none" id="work_pic3" type="file" name="work_pic3" placeholder="Work Picture">

                           <label for="" class="mt-4 text-muted badge">Upload your work images</label>
                           <div class="d-flex gap-3">
                            <img src="../../static/images/placeholder.avif" id="work_img1" style="width: 5rem; cursor: pointer;" alt="">
                            <img src="../../static/images/placeholder.avif" id="work_img2" style="width: 5rem; cursor: pointer;" alt="">
                            <img src="../../static/images/placeholder.avif" id="work_img3" style="width: 5rem; cursor: pointer;" alt="">
                           </div>

                           <div>
                            <select name="service_offered" id="" class="form-control shadow-none border">
                                <option value="" selected disabled>Choose services</option>
                                {% for serve in servs %}
                                    <option value="{{serve.id}}">{{serve.name}}</option>
                                {% endfor %}
                            </select>
                           </div>
                        </div>

                        <div class="form-button mt-3">
                            <button class="btn btn-primary p-2 fw-normal" id="login_btn" type="submit">
                                Complete
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700;900&display=swap');

*, body {
    font-family: 'Poppins', sans-serif;
    font-weight: 400;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
    -moz-osx-font-smoothing: grayscale;
}

html, body {
    /* height: 100%; */
    /* background-color: #152733; */
    overflow-y: auto;
    overflow-x: hidden;
}

.form-content input[type=text], .form-content input[type=password], 
.form-content input[type=email], .form-content select, 
.form-content input[type=tel], .form-content input[type=file] {
    width: 100%;
    padding: 9px 20px;
    text-align: left;
    border: 1px solid rgb(142, 131, 131);
    outline: 0;
    border-radius: 6px;
    background-color: #fff;
    font-size: 15px;
    font-weight: 300;
    color: #8D8D8D;
    -webkit-transition: all 0.3s ease;
    transition: all 0.3s ease;
    margin-top: 16px;
    box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 2px 0px !important;
}

.fa-solid.fa-image{
    cursor: pointer;
}

/* media query */
@media screen and (max-width: 768px) {
    .form-holder, #list_admins{
        width: 85% !important;
    }
}

</style>

<script>
    work_pic1 = document.getElementById('work_pic1');
    work_pic2 = document.getElementById('work_pic2');
    work_pic3 = document.getElementById('work_pic3');

    work_img1 = document.getElementById('work_img1');
    work_img2 = document.getElementById('work_img2');
    work_img3 = document.getElementById('work_img3');

    document.addEventListener('DOMContentLoaded', function () {
        const rateInput = document.getElementById('rate_input');
        const rateRadio = document.getElementById('rate');
        const contactPriceRadio = document.getElementById('contact_price');

        function handleRadioChange() {
            if (contactPriceRadio.checked) {
                rateInput.value = ''; // Clear the input field
                rateInput.disabled = true;
                rateInput.removeAttribute('required'); // Remove 'required' attribute
            } else {
                rateInput.disabled = false;
                rateInput.setAttribute('required', true); // Set 'required' attribute
            }
        }

        rateRadio.addEventListener('change', handleRadioChange);
        contactPriceRadio.addEventListener('change', handleRadioChange);

        // Initialize disabled state and 'required' attribute based on initial radio button checked state
        handleRadioChange();
    });

    work_img1.addEventListener('click', function() {
        work_pic1.click();
    });

    work_img2.addEventListener('click', function() {
        work_pic2.click();
    });

    work_img3.addEventListener('click', function() {
        work_pic3.click();
    });

    const handleImagePreview = (inputElement, imgElement) => {
    inputElement.addEventListener('change', () => {
        if (inputElement.files && inputElement.files[0]) {
            imgElement.src = URL.createObjectURL(inputElement.files[0]);
        }
    });
};


    handleImagePreview(work_pic1, work_img1);
    handleImagePreview(work_pic2, work_img2);
    handleImagePreview(work_pic3, work_img3);

</script>





{% endblock content %}